"""
Recommendation domain model.

Recommendations are actionable suggestions generated by the intelligence layer.
They are role-specific and prioritized by impact.
"""

from pydantic import BaseModel, Field
from typing import Optional, List, Dict, Any
from datetime import datetime, timezone
from enum import Enum


class RecommendationPriority(str, Enum):
    """Priority levels for recommendations."""
    CRITICAL = "critical"  # Must address immediately
    HIGH = "high"          # Should address soon
    MEDIUM = "medium"      # Address when convenient
    LOW = "low"            # Nice to have
    INFO = "info"          # Informational only


class RecommendationCategory(str, Enum):
    """Categories of recommendations."""
    CODE_QUALITY = "code_quality"
    SECURITY = "security"
    TESTING = "testing"
    PERFORMANCE = "performance"
    ARCHITECTURE = "architecture"
    PROCESS = "process"
    COLLABORATION = "collaboration"
    DEPLOYMENT = "deployment"


class RecommendationStatus(str, Enum):
    """Status of a recommendation."""
    PENDING = "pending"          # Not yet addressed
    ACCEPTED = "accepted"        # User accepted and will implement
    IMPLEMENTED = "implemented"  # Action taken
    REJECTED = "rejected"        # User chose not to implement
    OBSOLETE = "obsolete"        # No longer relevant


class Recommendation(BaseModel):
    """
    A single actionable recommendation.
    
    Generated by intelligence layer based on evidence analysis.
    """
    
    id: str = Field(..., description="Unique recommendation ID")
    
    # Context
    entity_type: str = Field(..., description="Type of entity (pr, task, sprint, etc.)")
    entity_id: str = Field(..., description="ID of related entity")
    project_id: Optional[str] = Field(None, description="Associated project")
    
    # Recommendation content
    title: str = Field(..., description="Short recommendation title")
    description: str = Field(..., description="Detailed explanation")
    action: str = Field(..., description="Specific action to take")
    
    # Classification
    category: RecommendationCategory
    priority: RecommendationPriority
    
    # Evidence
    reasoning: str = Field(..., description="Why this recommendation was generated")
    evidence_ids: List[str] = Field(default_factory=list, description="Related evidence/analysis IDs")
    confidence: float = Field(default=0.8, description="AI confidence score (0-1)")
    
    # Role targeting
    target_roles: List[str] = Field(default_factory=list, description="Roles this is relevant for")
    target_user_id: Optional[str] = Field(None, description="Specific user if applicable")
    
    # Impact
    estimated_impact: str = Field(default="medium", description="Expected impact if implemented")
    estimated_effort: str = Field(default="medium", description="Effort required (low/medium/high)")
    
    # Status tracking
    status: RecommendationStatus = Field(default=RecommendationStatus.PENDING)
    status_updated_at: Optional[str] = Field(None)
    status_updated_by: Optional[str] = Field(None)
    
    # Implementation tracking
    implementation_notes: Optional[str] = Field(None)
    related_pr_id: Optional[str] = Field(None, description="PR that implements this recommendation")
    
    # Metadata
    generated_by: str = Field(default="system", description="Agent/service that generated this")
    generated_at: str = Field(
        default_factory=lambda: datetime.now(timezone.utc).isoformat()
    )
    expires_at: Optional[str] = Field(None, description="When recommendation becomes obsolete")
    
    class Config:
        json_schema_extra = {
            "example": {
                "id": "REC-ABC123",
                "entity_type": "pull_request",
                "entity_id": "PR-001",
                "project_id": "PROJ-001",
                "title": "Add unit tests for authentication module",
                "description": "The authentication module has 0% test coverage, creating deployment risk.",
                "action": "Write unit tests covering login, logout, and token refresh flows",
                "category": "testing",
                "priority": "high",
                "reasoning": "Files in auth/ directory have high complexity and no test coverage",
                "confidence": 0.92,
                "target_roles": ["developer", "qa"],
                "target_user_id": "USER-123",
                "estimated_impact": "high",
                "estimated_effort": "medium",
                "status": "pending",
                "generated_by": "code-agent"
            }
        }
